export const FETCH_COINS_REQUEST = 'FETCH_COINS_REQUEST';
export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_COINS_ERROR = 'FETCH_COINS_ERROR';

export const FETCH_TITULARES_REQUEST = 'FETCH_TITULARES_REQUEST';
export const FETCH_TITULARES_SUCCESS = 'FETCH_TITULARES_SUCCESS';
export const FETCH_TITULARES_ERROR = 'FETCH_TITULARES_ERROR';

export const DELETE_TITULARES_REQUEST = 'DELETE_TITULARES_REQUEST';
export const DELETE_TITULARES_SUCCESS = 'DELETE_TITULARES_SUCCESS';
export const DELETE_TITULARES_ERROR = 'DELETE_TITULARES_ERROR';

export const UPDATE_TITULARES_REQUEST = 'UPDATE_TITULARES_REQUEST';
export const UPDATE_TITULARES_SUCCESS = 'UPDATE_TITULARES_SUCCESS';
export const UPDATE_TITULARES_ERROR = 'UPDATE_TITULARES_ERROR';

export const ADD_TITULARES_REQUEST = 'ADD_TITULARES_REQUEST';
export const ADD_TITULARES_SUCCESS = 'ADD_TITULARES_SUCCESS';
export const ADD_TITULARES_ERROR = 'ADD_TITULARES_ERROR';

export const FETCH_TIPOS_PERSONA_REQUEST = 'FETCH_TIPOS_PERSONA_REQUEST';
export const FETCH_TIPOS_PERSONA_SUCCESS = 'FETCH_TIPOS_PERSONA_SUCCESS';
export const FETCH_TIPOS_PERSONA_ERROR = 'FETCH_TIPOS_PERSONA_ERROR';
